export type ThemeColors = {
    primary: string;
    planMode: string;
    selection: string;
    thinking: string;
    success: string;
    error: string;
    info: string;
    background: string;
    surface: string;
    dialogSurface: string;
    dimSeparator: string;
}

export type Theme = {
    name: string;
    colours: ThemeColors;
}

export const THEMES: Theme[] = [

    // ── NAVY / OCEAN ──────────────────────────────────────────────
    {
        name: "Nightfox",
        colours: {
            primary:       "#c94f6d",
            planMode:      "#f4a261",
            selection:     "#2e3a4a",
            thinking:      "#9d79d6",
            success:       "#81b29a",
            error:         "#c94f6d",
            info:          "#719cd6",
            background:    "#192330",
            surface:       "#212e3f",
            dialogSurface: "#29394f",
            dimSeparator:  "#3a4f65",
        },
    },
    {
        name: "Deep Sea",
        colours: {
            primary:       "#5cb8e4",
            planMode:      "#f0a500",
            selection:     "#1e3a4c",
            thinking:      "#7eb8d4",
            success:       "#4caf82",
            error:         "#e05c5c",
            info:          "#38bdf8",
            background:    "#0a1929",
            surface:       "#0d2137",
            dialogSurface: "#112840",
            dimSeparator:  "#1e3a52",
        },
    },
    {
        name: "Abyss",
        colours: {
            primary:       "#569cd6",
            planMode:      "#ce9178",
            selection:     "#153450",
            thinking:      "#9cdcfe",
            success:       "#6a9955",
            error:         "#f44747",
            info:          "#4ec9b0",
            background:    "#000c18",
            surface:       "#001628",
            dialogSurface: "#00213a",
            dimSeparator:  "#0d3050",
        },
    },
    {
        name: "Midnight Blue",
        colours: {
            primary:       "#7aa2f7",
            planMode:      "#e0af68",
            selection:     "#283457",
            thinking:      "#bb9af7",
            success:       "#9ece6a",
            error:         "#f7768e",
            info:          "#2ac3de",
            background:    "#1a1b2e",
            surface:       "#1f2335",
            dialogSurface: "#24283b",
            dimSeparator:  "#3b4261",
        },
    },
    {
        name: "Ocean Breeze",
        colours: {
            primary:       "#60b8d4",
            planMode:      "#f4c430",
            selection:     "#1f3a4a",
            thinking:      "#a0d8ef",
            success:       "#52c78e",
            error:         "#e05555",
            info:          "#29b6f6",
            background:    "#0d1f2d",
            surface:       "#112637",
            dialogSurface: "#162d40",
            dimSeparator:  "#1e3d52",
        },
    },
    {
        name: "Arctic Blue",
        colours: {
            primary:       "#88c0d0",
            planMode:      "#ebcb8b",
            selection:     "#2e3440",
            thinking:      "#81a1c1",
            success:       "#a3be8c",
            error:         "#bf616a",
            info:          "#5e81ac",
            background:    "#0f1923",
            surface:       "#161f2b",
            dialogSurface: "#1c2733",
            dimSeparator:  "#2a3542",
        },
    },
    {
        name: "Nautilus",
        colours: {
            primary:       "#4dbdcf",
            planMode:      "#f7b731",
            selection:     "#1a3040",
            thinking:      "#80cbc4",
            success:       "#43a67a",
            error:         "#ef5350",
            info:          "#26c6da",
            background:    "#071520",
            surface:       "#0c1c2c",
            dialogSurface: "#112435",
            dimSeparator:  "#1a3045",
        },
    },
    {
        name: "Tidal",
        colours: {
            primary:       "#48cae4",
            planMode:      "#ffd166",
            selection:     "#023e58",
            thinking:      "#90e0ef",
            success:       "#06d6a0",
            error:         "#ef476f",
            info:          "#118ab2",
            background:    "#03111a",
            surface:       "#051a28",
            dialogSurface: "#072233",
            dimSeparator:  "#0a3045",
        },
    },

    // ── PURPLE / VIOLET ───────────────────────────────────────────
    {
        name: "Tokyo Night",
        colours: {
            primary:       "#7aa2f7",
            planMode:      "#e0af68",
            selection:     "#283457",
            thinking:      "#bb9af7",
            success:       "#9ece6a",
            error:         "#f7768e",
            info:          "#2ac3de",
            background:    "#1a1b2e",
            surface:       "#1f2335",
            dialogSurface: "#24283b",
            dimSeparator:  "#3b4261",
        },
    },
    {
        name: "Dracula",
        colours: {
            primary:       "#bd93f9",
            planMode:      "#ffb86c",
            selection:     "#44475a",
            thinking:      "#ff79c6",
            success:       "#50fa7b",
            error:         "#ff5555",
            info:          "#8be9fd",
            background:    "#282a36",
            surface:       "#21222c",
            dialogSurface: "#44475a",
            dimSeparator:  "#6272a4",
        },
    },
    {
        name: "Rosé Pine",
        colours: {
            primary:       "#c4a7e7",
            planMode:      "#f6c177",
            selection:     "#26233a",
            thinking:      "#ebbcba",
            success:       "#31748f",
            error:         "#eb6f92",
            info:          "#9ccfd8",
            background:    "#191724",
            surface:       "#1f1d2e",
            dialogSurface: "#26233a",
            dimSeparator:  "#403d52",
        },
    },
    {
        name: "Catppuccin Mocha",
        colours: {
            primary:       "#cba6f7",
            planMode:      "#fab387",
            selection:     "#313244",
            thinking:      "#f5c2e7",
            success:       "#a6e3a1",
            error:         "#f38ba8",
            info:          "#89dceb",
            background:    "#1e1e2e",
            surface:       "#181825",
            dialogSurface: "#313244",
            dimSeparator:  "#45475a",
        },
    },
    {
        name: "Purple Haze",
        colours: {
            primary:       "#b39ddb",
            planMode:      "#ffcc80",
            selection:     "#311b52",
            thinking:      "#ce93d8",
            success:       "#80cbc4",
            error:         "#ef9a9a",
            info:          "#80deea",
            background:    "#150d24",
            surface:       "#1c1232",
            dialogSurface: "#231740",
            dimSeparator:  "#362060",
        },
    },
    {
        name: "Violet Dusk",
        colours: {
            primary:       "#a78bfa",
            planMode:      "#fb923c",
            selection:     "#3b2f6e",
            thinking:      "#c4b5fd",
            success:       "#34d399",
            error:         "#f87171",
            info:          "#38bdf8",
            background:    "#0f0d1e",
            surface:       "#14112a",
            dialogSurface: "#1a1638",
            dimSeparator:  "#2d2756",
        },
    },
    {
        name: "Nebula",
        colours: {
            primary:       "#9b59b6",
            planMode:      "#e67e22",
            selection:     "#2c1654",
            thinking:      "#d7bde2",
            success:       "#27ae60",
            error:         "#e74c3c",
            info:          "#2980b9",
            background:    "#0e0618",
            surface:       "#150b22",
            dialogSurface: "#1c0f2e",
            dimSeparator:  "#2e1a4a",
        },
    },
    {
        name: "Synthwave",
        colours: {
            primary:       "#f92aad",
            planMode:      "#f7cc58",
            selection:     "#3b1f5e",
            thinking:      "#b46ef5",
            success:       "#72f1b8",
            error:         "#fe4450",
            info:          "#03edf9",
            background:    "#261447",
            surface:       "#1a0e38",
            dialogSurface: "#2d1a50",
            dimSeparator:  "#49296b",
        },
    },
    {
        name: "Neon Dreams",
        colours: {
            primary:       "#e040fb",
            planMode:      "#ffea00",
            selection:     "#4a0070",
            thinking:      "#ea80fc",
            success:       "#69f0ae",
            error:         "#ff1744",
            info:          "#40c4ff",
            background:    "#1a0030",
            surface:       "#200040",
            dialogSurface: "#280050",
            dimSeparator:  "#3d0070",
        },
    },
    {
        name: "Amethyst",
        colours: {
            primary:       "#9c7fc0",
            planMode:      "#e8b85d",
            selection:     "#2e2045",
            thinking:      "#b8a0d8",
            success:       "#7ec8a0",
            error:         "#e07575",
            info:          "#7ab8d8",
            background:    "#131020",
            surface:       "#1a1530",
            dialogSurface: "#201a3c",
            dimSeparator:  "#302850",
        },
    },

    // ── GREEN / FOREST ────────────────────────────────────────────
    {
        name: "Everforest",
        colours: {
            primary:       "#a7c080",
            planMode:      "#e9c46a",
            selection:     "#2e383c",
            thinking:      "#d3c6aa",
            success:       "#83c092",
            error:         "#e67e80",
            info:          "#7fbbb3",
            background:    "#1e2326",
            surface:       "#272e33",
            dialogSurface: "#2e383c",
            dimSeparator:  "#415055",
        },
    },
    {
        name: "Jungle",
        colours: {
            primary:       "#4caf50",
            planMode:      "#ffc107",
            selection:     "#1b2e1d",
            thinking:      "#81c784",
            success:       "#66bb6a",
            error:         "#ef5350",
            info:          "#26c6da",
            background:    "#0a1a0c",
            surface:       "#0f2212",
            dialogSurface: "#142a18",
            dimSeparator:  "#1e3d22",
        },
    },
    {
        name: "Matrix",
        colours: {
            primary:       "#00ff41",
            planMode:      "#00cc33",
            selection:     "#003b00",
            thinking:      "#39ff14",
            success:       "#00e676",
            error:         "#ff1744",
            info:          "#00e5ff",
            background:    "#000300",
            surface:       "#000a00",
            dialogSurface: "#001200",
            dimSeparator:  "#001f00",
        },
    },
    {
        name: "Forest Mist",
        colours: {
            primary:       "#88b090",
            planMode:      "#c8a96e",
            selection:     "#263030",
            thinking:      "#a8c8a8",
            success:       "#78a878",
            error:         "#c87878",
            info:          "#78a8b8",
            background:    "#141e18",
            surface:       "#1a2620",
            dialogSurface: "#202e28",
            dimSeparator:  "#2e4038",
        },
    },
    {
        name: "Sage",
        colours: {
            primary:       "#8fbc8f",
            planMode:      "#d4ac6e",
            selection:     "#2a3428",
            thinking:      "#b0c8b0",
            success:       "#6dab6d",
            error:         "#cd6262",
            info:          "#6dabb0",
            background:    "#141a12",
            surface:       "#1c2418",
            dialogSurface: "#242e20",
            dimSeparator:  "#354030",
        },
    },
    {
        name: "Pine",
        colours: {
            primary:       "#31748f",
            planMode:      "#f6c177",
            selection:     "#1a2e2a",
            thinking:      "#9ccfd8",
            success:       "#a3be8c",
            error:         "#eb6f92",
            info:          "#88c0d0",
            background:    "#0d1a18",
            surface:       "#122020",
            dialogSurface: "#162828",
            dimSeparator:  "#1f3830",
        },
    },
    {
        name: "Bamboo",
        colours: {
            primary:       "#a8c66c",
            planMode:      "#e8c460",
            selection:     "#283020",
            thinking:      "#c0d890",
            success:       "#80b840",
            error:         "#e07060",
            info:          "#60b0c0",
            background:    "#121808",
            surface:       "#182010",
            dialogSurface: "#1e2a15",
            dimSeparator:  "#2c3c1e",
        },
    },
    {
        name: "Moss",
        colours: {
            primary:       "#7a9e7e",
            planMode:      "#c4a35a",
            selection:     "#253028",
            thinking:      "#9db89f",
            success:       "#5e9063",
            error:         "#b86060",
            info:          "#5e8b90",
            background:    "#111814",
            surface:       "#172018",
            dialogSurface: "#1c281e",
            dimSeparator:  "#2a382c",
        },
    },

    // ── RED / WARM ────────────────────────────────────────────────
    {
        name: "Crimson",
        colours: {
            primary:       "#dc143c",
            planMode:      "#ff8c00",
            selection:     "#3d0c14",
            thinking:      "#ff6b6b",
            success:       "#3cb371",
            error:         "#ff0000",
            info:          "#4169e1",
            background:    "#1a0008",
            surface:       "#240010",
            dialogSurface: "#2e0015",
            dimSeparator:  "#480020",
        },
    },
    {
        name: "Ember",
        colours: {
            primary:       "#e85d04",
            planMode:      "#faa307",
            selection:     "#370e00",
            thinking:      "#f48c06",
            success:       "#606c38",
            error:         "#dc2f02",
            info:          "#4895ef",
            background:    "#1a0900",
            surface:       "#240e00",
            dialogSurface: "#2e1200",
            dimSeparator:  "#451a00",
        },
    },
    {
        name: "Blood Moon",
        colours: {
            primary:       "#c0392b",
            planMode:      "#e67e22",
            selection:     "#2c0a0a",
            thinking:      "#e74c3c",
            success:       "#27ae60",
            error:         "#ff0000",
            info:          "#2980b9",
            background:    "#100000",
            surface:       "#180000",
            dialogSurface: "#220000",
            dimSeparator:  "#350000",
        },
    },
    {
        name: "Rust",
        colours: {
            primary:       "#b7410e",
            planMode:      "#d4813a",
            selection:     "#2e1808",
            thinking:      "#cd7f50",
            success:       "#6a8f4b",
            error:         "#c0392b",
            info:          "#4a7fa5",
            background:    "#170a04",
            surface:       "#1f1008",
            dialogSurface: "#28160a",
            dimSeparator:  "#3d2010",
        },
    },
    {
        name: "Volcanic",
        colours: {
            primary:       "#ff6b35",
            planMode:      "#ffd700",
            selection:     "#3a1a0a",
            thinking:      "#ff9a3c",
            success:       "#4caf50",
            error:         "#ff1744",
            info:          "#40a9ff",
            background:    "#1a0a00",
            surface:       "#241200",
            dialogSurface: "#2e1800",
            dimSeparator:  "#452400",
        },
    },
    {
        name: "Sunset",
        colours: {
            primary:       "#ff7043",
            planMode:      "#ffca28",
            selection:     "#3e1a08",
            thinking:      "#ff8a65",
            success:       "#66bb6a",
            error:         "#ef5350",
            info:          "#42a5f5",
            background:    "#1c0e00",
            surface:       "#241600",
            dialogSurface: "#2e1c00",
            dimSeparator:  "#422c00",
        },
    },
    {
        name: "Mars",
        colours: {
            primary:       "#cd5c5c",
            planMode:      "#daa520",
            selection:     "#2e1010",
            thinking:      "#d2691e",
            success:       "#5a8a5a",
            error:         "#b22222",
            info:          "#4682b4",
            background:    "#120808",
            surface:       "#1a0e0e",
            dialogSurface: "#221414",
            dimSeparator:  "#341e1e",
        },
    },

    // ── GREY / MONOCHROME ─────────────────────────────────────────
    {
        name: "One Dark",
        colours: {
            primary:       "#61afef",
            planMode:      "#d19a66",
            selection:     "#3e4451",
            thinking:      "#c678dd",
            success:       "#98c379",
            error:         "#e06c75",
            info:          "#56b6c2",
            background:    "#282c34",
            surface:       "#21252b",
            dialogSurface: "#2c313a",
            dimSeparator:  "#4b5263",
        },
    },
    {
        name: "Nord",
        colours: {
            primary:       "#88c0d0",
            planMode:      "#ebcb8b",
            selection:     "#3b4252",
            thinking:      "#81a1c1",
            success:       "#a3be8c",
            error:         "#bf616a",
            info:          "#5e81ac",
            background:    "#2e3440",
            surface:       "#272c36",
            dialogSurface: "#3b4252",
            dimSeparator:  "#434c5e",
        },
    },
    {
        name: "Gruvbox Dark",
        colours: {
            primary:       "#fabd2f",
            planMode:      "#fe8019",
            selection:     "#3c3836",
            thinking:      "#d3869b",
            success:       "#b8bb26",
            error:         "#fb4934",
            info:          "#83a598",
            background:    "#282828",
            surface:       "#1d2021",
            dialogSurface: "#32302f",
            dimSeparator:  "#504945",
        },
    },
    {
        name: "Monochrome",
        colours: {
            primary:       "#e0e0e0",
            planMode:      "#bdbdbd",
            selection:     "#3a3a3a",
            thinking:      "#9e9e9e",
            success:       "#a5d6a7",
            error:         "#ef9a9a",
            info:          "#90caf9",
            background:    "#121212",
            surface:       "#1e1e1e",
            dialogSurface: "#2a2a2a",
            dimSeparator:  "#3a3a3a",
        },
    },
    {
        name: "Charcoal",
        colours: {
            primary:       "#c8c8c8",
            planMode:      "#d4a855",
            selection:     "#3d3d3d",
            thinking:      "#a8a8a8",
            success:       "#88c888",
            error:         "#d87878",
            info:          "#78a8d8",
            background:    "#1e1e1e",
            surface:       "#252525",
            dialogSurface: "#2c2c2c",
            dimSeparator:  "#3c3c3c",
        },
    },
    {
        name: "Obsidian",
        colours: {
            primary:       "#a9b7c6",
            planMode:      "#ffc66d",
            selection:     "#214283",
            thinking:      "#cc7832",
            success:       "#629755",
            error:         "#bc3f3c",
            info:          "#6897bb",
            background:    "#2b2b2b",
            surface:       "#222222",
            dialogSurface: "#313335",
            dimSeparator:  "#4e5254",
        },
    },
    {
        name: "Carbon",
        colours: {
            primary:       "#78a9ff",
            planMode:      "#f1c21b",
            selection:     "#393939",
            thinking:      "#be95ff",
            success:       "#42be65",
            error:         "#fa4d56",
            info:          "#33b1ff",
            background:    "#161616",
            surface:       "#1e1e1e",
            dialogSurface: "#262626",
            dimSeparator:  "#393939",
        },
    },
    {
        name: "Slate",
        colours: {
            primary:       "#94a3b8",
            planMode:      "#f59e0b",
            selection:     "#334155",
            thinking:      "#cbd5e1",
            success:       "#4ade80",
            error:         "#f87171",
            info:          "#60a5fa",
            background:    "#0f172a",
            surface:       "#1e293b",
            dialogSurface: "#334155",
            dimSeparator:  "#475569",
        },
    },
    {
        name: "Ink",
        colours: {
            primary:       "#d4d4d4",
            planMode:      "#dcdcaa",
            selection:     "#264f78",
            thinking:      "#c586c0",
            success:       "#4ec9b0",
            error:         "#f44747",
            info:          "#9cdcfe",
            background:    "#1e1e1e",
            surface:       "#252526",
            dialogSurface: "#2d2d30",
            dimSeparator:  "#3c3c3c",
        },
    },
    {
        name: "Ash",
        colours: {
            primary:       "#b8bcc8",
            planMode:      "#c8a86e",
            selection:     "#383c48",
            thinking:      "#9098b0",
            success:       "#82b882",
            error:         "#c87878",
            info:          "#7898c8",
            background:    "#1c1e26",
            surface:       "#22242e",
            dialogSurface: "#282c38",
            dimSeparator:  "#383c4a",
        },
    },

    // ── BROWN / EARTHY ────────────────────────────────────────────
    {
        name: "Gruvbox Material",
        colours: {
            primary:       "#e8c99a",
            planMode:      "#e0a870",
            selection:     "#3c3528",
            thinking:      "#d4be98",
            success:       "#a9b665",
            error:         "#ea6962",
            info:          "#7daea3",
            background:    "#1d2021",
            surface:       "#282828",
            dialogSurface: "#32302f",
            dimSeparator:  "#45403d",
        },
    },
    {
        name: "Coffee",
        colours: {
            primary:       "#c4956a",
            planMode:      "#d4a85a",
            selection:     "#2e2018",
            thinking:      "#b8866a",
            success:       "#7a9858",
            error:         "#c86858",
            info:          "#6888a8",
            background:    "#180e08",
            surface:       "#201610",
            dialogSurface: "#281e16",
            dimSeparator:  "#382c22",
        },
    },
    {
        name: "Walnut",
        colours: {
            primary:       "#b8895a",
            planMode:      "#c8a048",
            selection:     "#2a1e14",
            thinking:      "#c8a880",
            success:       "#6a8850",
            error:         "#b86050",
            info:          "#5880a8",
            background:    "#130d08",
            surface:       "#1c140e",
            dialogSurface: "#251b14",
            dimSeparator:  "#38271c",
        },
    },
    {
        name: "Sandstorm",
        colours: {
            primary:       "#d4b896",
            planMode:      "#c8903c",
            selection:     "#2e2818",
            thinking:      "#e0c8a0",
            success:       "#7a9060",
            error:         "#c06858",
            info:          "#5888a8",
            background:    "#1a1508",
            surface:       "#221c10",
            dialogSurface: "#2c2418",
            dimSeparator:  "#3e3422",
        },
    },
    {
        name: "Mocha",
        colours: {
            primary:       "#a07850",
            planMode:      "#b89060",
            selection:     "#28201a",
            thinking:      "#b89070",
            success:       "#608050",
            error:         "#a85848",
            info:          "#507890",
            background:    "#100c08",
            surface:       "#181410",
            dialogSurface: "#201a15",
            dimSeparator:  "#302820",
        },
    },

    // ── TEAL / CYAN ───────────────────────────────────────────────
    {
        name: "Teal Dark",
        colours: {
            primary:       "#00bcd4",
            planMode:      "#ffb300",
            selection:     "#00363a",
            thinking:      "#80deea",
            success:       "#00c853",
            error:         "#d50000",
            info:          "#0091ea",
            background:    "#001a1c",
            surface:       "#002326",
            dialogSurface: "#002c30",
            dimSeparator:  "#00404a",
        },
    },
    {
        name: "Cyan Storm",
        colours: {
            primary:       "#00e5ff",
            planMode:      "#ffd740",
            selection:     "#003344",
            thinking:      "#80ffff",
            success:       "#00e676",
            error:         "#ff5252",
            info:          "#448aff",
            background:    "#001520",
            surface:       "#001e2e",
            dialogSurface: "#00263a",
            dimSeparator:  "#003850",
        },
    },
    {
        name: "Aquamarine",
        colours: {
            primary:       "#7fffd4",
            planMode:      "#ffc200",
            selection:     "#124040",
            thinking:      "#64e0c0",
            success:       "#48c774",
            error:         "#f14668",
            info:          "#3273dc",
            background:    "#061e20",
            surface:       "#0c2a2a",
            dialogSurface: "#123434",
            dimSeparator:  "#1c4848",
        },
    },
    {
        name: "Spearmint",
        colours: {
            primary:       "#50e3c2",
            planMode:      "#fac863",
            selection:     "#0e2e28",
            thinking:      "#7edbbf",
            success:       "#a8e6cf",
            error:         "#ff6b9d",
            info:          "#74b9ff",
            background:    "#061a16",
            surface:       "#0c2420",
            dialogSurface: "#122e28",
            dimSeparator:  "#1c4038",
        },
    },
    {
        name: "Seafoam",
        colours: {
            primary:       "#64d8cb",
            planMode:      "#ffd54f",
            selection:     "#0f302e",
            thinking:      "#80cbc4",
            success:       "#69f0ae",
            error:         "#ff5252",
            info:          "#40c4ff",
            background:    "#051a18",
            surface:       "#0c2422",
            dialogSurface: "#122e2c",
            dimSeparator:  "#1c4240",
        },
    },
    {
        name: "Glacier",
        colours: {
            primary:       "#88d8e8",
            planMode:      "#f0c070",
            selection:     "#1a3040",
            thinking:      "#a0dce8",
            success:       "#70c890",
            error:         "#e07080",
            info:          "#70a8e0",
            background:    "#0a1820",
            surface:       "#102028",
            dialogSurface: "#162830",
            dimSeparator:  "#223848",
        },
    },

    // ── YELLOW / GOLD ─────────────────────────────────────────────
    {
        name: "Solar",
        colours: {
            primary:       "#fbbf24",
            planMode:      "#f97316",
            selection:     "#3d2e00",
            thinking:      "#fcd34d",
            success:       "#34d399",
            error:         "#f87171",
            info:          "#60a5fa",
            background:    "#1c1600",
            surface:       "#261e00",
            dialogSurface: "#302600",
            dimSeparator:  "#453800",
        },
    },
    {
        name: "Gold Rush",
        colours: {
            primary:       "#ffd700",
            planMode:      "#ffa500",
            selection:     "#3a2e00",
            thinking:      "#ffe066",
            success:       "#50c878",
            error:         "#dc143c",
            info:          "#1e90ff",
            background:    "#1a1500",
            surface:       "#231d00",
            dialogSurface: "#2d2500",
            dimSeparator:  "#453900",
        },
    },
    {
        name: "Amber",
        colours: {
            primary:       "#ffbf00",
            planMode:      "#ff7043",
            selection:     "#332500",
            thinking:      "#ffd54f",
            success:       "#4caf50",
            error:         "#f44336",
            info:          "#2196f3",
            background:    "#171200",
            surface:       "#201900",
            dialogSurface: "#2a2100",
            dimSeparator:  "#3d3100",
        },
    },
    {
        name: "Saffron",
        colours: {
            primary:       "#f4a400",
            planMode:      "#e06010",
            selection:     "#302000",
            thinking:      "#f8c060",
            success:       "#60a060",
            error:         "#c04040",
            info:          "#4080c0",
            background:    "#161000",
            surface:       "#1e1600",
            dialogSurface: "#281e00",
            dimSeparator:  "#3c2e00",
        },
    },

    // ── PINK / ROSE ───────────────────────────────────────────────
    {
        name: "Sakura",
        colours: {
            primary:       "#f8b4c8",
            planMode:      "#f9d4a0",
            selection:     "#3a1a28",
            thinking:      "#e8a0c0",
            success:       "#90c890",
            error:         "#e06080",
            info:          "#80a8e0",
            background:    "#1e0e18",
            surface:       "#281420",
            dialogSurface: "#321a28",
            dimSeparator:  "#482838",
        },
    },
    {
        name: "Rose Gold",
        colours: {
            primary:       "#e8a0a0",
            planMode:      "#d4a060",
            selection:     "#2e1c1c",
            thinking:      "#d4b4b4",
            success:       "#80b880",
            error:         "#c85858",
            info:          "#7898c8",
            background:    "#1a1010",
            surface:       "#221818",
            dialogSurface: "#2c2020",
            dimSeparator:  "#3e2e2e",
        },
    },
    {
        name: "Flamingo",
        colours: {
            primary:       "#fc8eac",
            planMode:      "#ffcc88",
            selection:     "#40182a",
            thinking:      "#f4a0c0",
            success:       "#7ac8a0",
            error:         "#e85078",
            info:          "#78a8e8",
            background:    "#200a14",
            surface:       "#2a1020",
            dialogSurface: "#34162a",
            dimSeparator:  "#4a2238",
        },
    },
    {
        name: "Bubblegum",
        colours: {
            primary:       "#ff77aa",
            planMode:      "#ff9944",
            selection:     "#3d1830",
            thinking:      "#ff99cc",
            success:       "#55cc88",
            error:         "#ff4488",
            info:          "#44aaff",
            background:    "#1e0c18",
            surface:       "#281220",
            dialogSurface: "#321828",
            dimSeparator:  "#482438",
        },
    },
    {
        name: "Orchid",
        colours: {
            primary:       "#da70d6",
            planMode:      "#daa520",
            selection:     "#2e1030",
            thinking:      "#ee82ee",
            success:       "#3cb371",
            error:         "#cd5c5c",
            info:          "#4169e1",
            background:    "#160818",
            surface:       "#1e1020",
            dialogSurface: "#261528",
            dimSeparator:  "#3a2038",
        },
    },

    // ── MIXED / UNIQUE PALETTES ───────────────────────────────────
    {
        name: "Horizon",
        colours: {
            primary:       "#e95678",
            planMode:      "#fab795",
            selection:     "#1c3644",
            thinking:      "#f09383",
            success:       "#29d398",
            error:         "#e95678",
            info:          "#25b0e8",
            background:    "#1c1e26",
            surface:       "#232530",
            dialogSurface: "#2e303e",
            dimSeparator:  "#3d3f4e",
        },
    },
    {
        name: "Moonlight",
        colours: {
            primary:       "#82aaff",
            planMode:      "#ffc777",
            selection:     "#2d3f76",
            thinking:      "#c099ff",
            success:       "#c3e88d",
            error:         "#ff757f",
            info:          "#89ddff",
            background:    "#1e2030",
            surface:       "#191a2a",
            dialogSurface: "#222436",
            dimSeparator:  "#363a4f",
        },
    },
    {
        name: "Kanagawa",
        colours: {
            primary:       "#7e9cd8",
            planMode:      "#dca561",
            selection:     "#2d4f67",
            thinking:      "#957fb8",
            success:       "#76946a",
            error:         "#c34043",
            info:          "#6a9589",
            background:    "#1f1f28",
            surface:       "#16161d",
            dialogSurface: "#2a2a37",
            dimSeparator:  "#363646",
        },
    },
    {
        name: "Solarized Dark",
        colours: {
            primary:       "#268bd2",
            planMode:      "#b58900",
            selection:     "#073642",
            thinking:      "#6c71c4",
            success:       "#859900",
            error:         "#dc322f",
            info:          "#2aa198",
            background:    "#002b36",
            surface:       "#073642",
            dialogSurface: "#0d4050",
            dimSeparator:  "#586e75",
        },
    },
    {
        name: "Palenight",
        colours: {
            primary:       "#82aaff",
            planMode:      "#ffcb6b",
            selection:     "#34324a",
            thinking:      "#c792ea",
            success:       "#c3e88d",
            error:         "#f07178",
            info:          "#89ddff",
            background:    "#292d3e",
            surface:       "#232635",
            dialogSurface: "#34324a",
            dimSeparator:  "#4b4e6d",
        },
    },
    {
        name: "Cobalt2",
        colours: {
            primary:       "#ffc600",
            planMode:      "#ff9d00",
            selection:     "#1f4e78",
            thinking:      "#ff628c",
            success:       "#3ad900",
            error:         "#f44747",
            info:          "#0088ff",
            background:    "#193549",
            surface:       "#122838",
            dialogSurface: "#1f4060",
            dimSeparator:  "#2a5580",
        },
    },
    {
        name: "Shades of Purple",
        colours: {
            primary:       "#fad000",
            planMode:      "#ff9d00",
            selection:     "#342a5a",
            thinking:      "#fb94ff",
            success:       "#3ad900",
            error:         "#f44747",
            info:          "#9effff",
            background:    "#2d2b55",
            surface:       "#1e1e3f",
            dialogSurface: "#342a5a",
            dimSeparator:  "#4a3b7a",
        },
    },
    {
        name: "Night Owl",
        colours: {
            primary:       "#82aaff",
            planMode:      "#ffcb8b",
            selection:     "#1d3b53",
            thinking:      "#c792ea",
            success:       "#addb67",
            error:         "#ff5874",
            info:          "#7fdbca",
            background:    "#011627",
            surface:       "#01111d",
            dialogSurface: "#0b2942",
            dimSeparator:  "#1b3a50",
        },
    },
    {
        name: "Monokai",
        colours: {
            primary:       "#a6e22e",
            planMode:      "#e6db74",
            selection:     "#49483e",
            thinking:      "#ae81ff",
            success:       "#a6e22e",
            error:         "#f92672",
            info:          "#66d9e8",
            background:    "#272822",
            surface:       "#1e1f1c",
            dialogSurface: "#35342c",
            dimSeparator:  "#49483e",
        },
    },
    {
        name: "Panda",
        colours: {
            primary:       "#19f9d8",
            planMode:      "#ffb86c",
            selection:     "#29343d",
            thinking:      "#ff75b5",
            success:       "#19f9d8",
            error:         "#ff2c6d",
            info:          "#45a9f9",
            background:    "#1a1a1a",
            surface:       "#151515",
            dialogSurface: "#292929",
            dimSeparator:  "#383838",
        },
    },
    {
        name: "Dark Plus",
        colours: {
            primary:       "#4fc1ff",
            planMode:      "#ce9178",
            selection:     "#264f78",
            thinking:      "#c586c0",
            success:       "#4ec9b0",
            error:         "#f44747",
            info:          "#9cdcfe",
            background:    "#1e1e1e",
            surface:       "#252526",
            dialogSurface: "#2d2d30",
            dimSeparator:  "#3c3c3c",
        },
    },
    {
        name: "Atom One Dark",
        colours: {
            primary:       "#61afef",
            planMode:      "#e5c07b",
            selection:     "#3e4451",
            thinking:      "#c678dd",
            success:       "#98c379",
            error:         "#e06c75",
            info:          "#56b6c2",
            background:    "#282c34",
            surface:       "#21252b",
            dialogSurface: "#2c313c",
            dimSeparator:  "#4b5263",
        },
    },
    {
        name: "Ayu Dark",
        colours: {
            primary:       "#ffb454",
            planMode:      "#e6b673",
            selection:     "#273747",
            thinking:      "#d2a6ff",
            success:       "#aad94c",
            error:         "#f28779",
            info:          "#39bae6",
            background:    "#0d1017",
            surface:       "#131721",
            dialogSurface: "#1a2030",
            dimSeparator:  "#252f40",
        },
    },
    {
        name: "Iceberg",
        colours: {
            primary:       "#84a0c6",
            planMode:      "#e2a478",
            selection:     "#1e2132",
            thinking:      "#a093c7",
            success:       "#b4be82",
            error:         "#e27878",
            info:          "#89b8c2",
            background:    "#161821",
            surface:       "#0f1117",
            dialogSurface: "#1e2132",
            dimSeparator:  "#2e3244",
        },
    },
    {
        name: "Spacegray",
        colours: {
            primary:       "#b0c4de",
            planMode:      "#d4aa60",
            selection:     "#343d46",
            thinking:      "#ab7967",
            success:       "#a1b56c",
            error:         "#ab4642",
            info:          "#7cafc2",
            background:    "#1c2028",
            surface:       "#252b34",
            dialogSurface: "#2e3540",
            dimSeparator:  "#404956",
        },
    },
    {
        name: "Fairy Floss",
        colours: {
            primary:       "#ffb8d1",
            planMode:      "#ffe6b3",
            selection:     "#3d1f3f",
            thinking:      "#e3b8f7",
            success:       "#b8f7d0",
            error:         "#ff6e6e",
            info:          "#b3ecff",
            background:    "#1a0a1f",
            surface:       "#231130",
            dialogSurface: "#2d183e",
            dimSeparator:  "#402550",
        },
    },
    {
        name: "Halcyon",
        colours: {
            primary:       "#5ccfe6",
            planMode:      "#ffd580",
            selection:     "#1d2530",
            thinking:      "#c3a6ff",
            success:       "#bae67e",
            error:         "#ff3333",
            info:          "#5ccfe6",
            background:    "#1d2433",
            surface:       "#171e2e",
            dialogSurface: "#232d40",
            dimSeparator:  "#2d3a50",
        },
    },
    {
        name: "Noctis",
        colours: {
            primary:       "#7ebfc4",
            planMode:      "#f0b775",
            selection:     "#1b3044",
            thinking:      "#acb4fb",
            success:       "#7fd13b",
            error:         "#de5656",
            info:          "#49adb5",
            background:    "#0a1a2a",
            surface:       "#0f2234",
            dialogSurface: "#162c40",
            dimSeparator:  "#1f3c54",
        },
    },
    {
        name: "Oceanic Next",
        colours: {
            primary:       "#66cccc",
            planMode:      "#f99157",
            selection:     "#2b2f33",
            thinking:      "#cc99cc",
            success:       "#99cc99",
            error:         "#ec5f67",
            info:          "#6699cc",
            background:    "#1b2b34",
            surface:       "#152228",
            dialogSurface: "#232a30",
            dimSeparator:  "#343d46",
        },
    },
    {
        name: "Zenburn",
        colours: {
            primary:       "#dcdccc",
            planMode:      "#e0cf9f",
            selection:     "#3f3f3f",
            thinking:      "#cc9393",
            success:       "#7f9f7f",
            error:         "#cc9393",
            info:          "#8cd0d3",
            background:    "#3f3f3f",
            surface:       "#383838",
            dialogSurface: "#4f4f4f",
            dimSeparator:  "#5f5f5f",
        },
    },
    {
        name: "Firewatch",
        colours: {
            primary:       "#d06479",
            planMode:      "#e8a060",
            selection:     "#2e2030",
            thinking:      "#c08890",
            success:       "#70a878",
            error:         "#c04060",
            info:          "#6888c0",
            background:    "#18101c",
            surface:       "#201620",
            dialogSurface: "#281e28",
            dimSeparator:  "#3a2c3c",
        },
    },
    {
        name: "Mariana",
        colours: {
            primary:       "#5fb4b4",
            planMode:      "#fac761",
            selection:     "#2d3441",
            thinking:      "#c695c6",
            success:       "#99c794",
            error:         "#ec5f66",
            info:          "#6dcbea",
            background:    "#1a1e28",
            surface:       "#141820",
            dialogSurface: "#222838",
            dimSeparator:  "#303848",
        },
    },
    {
        name: "Darcula",
        colours: {
            primary:       "#a9b7c6",
            planMode:      "#bbb529",
            selection:     "#214283",
            thinking:      "#9876aa",
            success:       "#629755",
            error:         "#bc3f3c",
            info:          "#6897bb",
            background:    "#2b2b2b",
            surface:       "#313335",
            dialogSurface: "#3c3f41",
            dimSeparator:  "#515151",
        },
    },
    {
        name: "Material Darker",
        colours: {
            primary:       "#80cbc4",
            planMode:      "#ffcb6b",
            selection:     "#1f2233",
            thinking:      "#c792ea",
            success:       "#c3e88d",
            error:         "#f07178",
            info:          "#89ddff",
            background:    "#212121",
            surface:       "#1a1a1a",
            dialogSurface: "#2c2c2c",
            dimSeparator:  "#424242",
        },
    },
    {
        name: "Andromeda",
        colours: {
            primary:       "#00e8c6",
            planMode:      "#ffe66d",
            selection:     "#00aaa0",
            thinking:      "#e9779c",
            success:       "#00e8c6",
            error:         "#f0616d",
            info:          "#25b2bc",
            background:    "#23262e",
            surface:       "#1b1e26",
            dialogSurface: "#2b2f38",
            dimSeparator:  "#404450",
        },
    },
    {
        name: "Bluloco Dark",
        colours: {
            primary:       "#10b1fe",
            planMode:      "#ff936a",
            selection:     "#1b2e44",
            thinking:      "#9f7efe",
            success:       "#3fc56b",
            error:         "#ff6480",
            info:          "#3691ff",
            background:    "#282a36",
            surface:       "#1e2030",
            dialogSurface: "#293050",
            dimSeparator:  "#3d4560",
        },
    },
    {
        name: "Outrun",
        colours: {
            primary:       "#ff4499",
            planMode:      "#ffdd00",
            selection:     "#2c1654",
            thinking:      "#bb88ff",
            success:       "#00ffcc",
            error:         "#ff2244",
            info:          "#00ccff",
            background:    "#0d0821",
            surface:       "#150c2e",
            dialogSurface: "#1c1040",
            dimSeparator:  "#2d1a5e",
        },
    },
    {
        name: "Cyberpunk",
        colours: {
            primary:       "#00ffff",
            planMode:      "#ffff00",
            selection:     "#1a1a3a",
            thinking:      "#ff00ff",
            success:       "#00ff66",
            error:         "#ff0033",
            info:          "#0099ff",
            background:    "#0a0a1a",
            surface:       "#111128",
            dialogSurface: "#181832",
            dimSeparator:  "#252548",
        },
    },
    {
        name: "Vapor",
        colours: {
            primary:       "#ff71ce",
            planMode:      "#fffb96",
            selection:     "#1c1040",
            thinking:      "#b967ff",
            success:       "#05ffa1",
            error:         "#ff2079",
            info:          "#01cdfe",
            background:    "#0c0820",
            surface:       "#120e2e",
            dialogSurface: "#18143c",
            dimSeparator:  "#261e54",
        },
    },
    {
        name: "Tropical",
        colours: {
            primary:       "#00e5cc",
            planMode:      "#ffe066",
            selection:     "#0a2e28",
            thinking:      "#80f0d8",
            success:       "#55dd88",
            error:         "#ff5566",
            info:          "#44bbff",
            background:    "#051a16",
            surface:       "#0a2420",
            dialogSurface: "#0f2e28",
            dimSeparator:  "#184038",
        },
    },
    {
        name: "Witch Hazel",
        colours: {
            primary:       "#ff8adb",
            planMode:      "#ffd580",
            selection:     "#3a2648",
            thinking:      "#d6acff",
            success:       "#b8f0a8",
            error:         "#ff6188",
            info:          "#a8d8ff",
            background:    "#1c1527",
            surface:       "#241e30",
            dialogSurface: "#2e2640",
            dimSeparator:  "#3e3452",
        },
    },
    {
        name: "Radical",
        colours: {
            primary:       "#ff006b",
            planMode:      "#ffb800",
            selection:     "#2a0a2e",
            thinking:      "#ff79c6",
            success:       "#40ff80",
            error:         "#ff0000",
            info:          "#40c0ff",
            background:    "#141020",
            surface:       "#1a1428",
            dialogSurface: "#201a30",
            dimSeparator:  "#302840",
        },
    },
    {
        name: "Laserwave",
        colours: {
            primary:       "#fc199a",
            planMode:      "#f7b93e",
            selection:     "#2e1a4a",
            thinking:      "#b45bcf",
            success:       "#69e06a",
            error:         "#fd1015",
            info:          "#7af8ca",
            background:    "#1a0933",
            surface:       "#220e40",
            dialogSurface: "#2c1250",
            dimSeparator:  "#3e1a68",
        },
    },
    {
        name: "Gotham",
        colours: {
            primary:       "#599cab",
            planMode:      "#d26939",
            selection:     "#0d3640",
            thinking:      "#a8a384",
            success:       "#84a150",
            error:         "#c23b22",
            info:          "#2a7fac",
            background:    "#0a1e26",
            surface:       "#0d2430",
            dialogSurface: "#0f2c3a",
            dimSeparator:  "#163e50",
        },
    },
    {
        name: "Merbivore",
        colours: {
            primary:       "#fd971f",
            planMode:      "#e6db74",
            selection:     "#48180c",
            thinking:      "#ae81ff",
            success:       "#a6e22e",
            error:         "#f92672",
            info:          "#66d9e8",
            background:    "#1c0a00",
            surface:       "#250e00",
            dialogSurface: "#2e1200",
            dimSeparator:  "#451c00",
        },
    },
    {
        name: "Tomorrow Night",
        colours: {
            primary:       "#81a2be",
            planMode:      "#de935f",
            selection:     "#373b41",
            thinking:      "#b294bb",
            success:       "#b5bd68",
            error:         "#cc6666",
            info:          "#8abeb7",
            background:    "#1d1f21",
            surface:       "#161719",
            dialogSurface: "#282a2e",
            dimSeparator:  "#373b41",
        },
    },
    {
        name: "Palenight HC",
        colours: {
            primary:       "#91b4d5",
            planMode:      "#d3b987",
            selection:     "#292d3e",
            thinking:      "#b490c0",
            success:       "#aec098",
            error:         "#c17e85",
            info:          "#87b3c2",
            background:    "#0e0d17",
            surface:       "#14121e",
            dialogSurface: "#1a1828",
            dimSeparator:  "#2a2840",
        },
    },
    {
        name: "Hacker",
        colours: {
            primary:       "#33ff33",
            planMode:      "#66ff00",
            selection:     "#003300",
            thinking:      "#00cc00",
            success:       "#00ff66",
            error:         "#ff3300",
            info:          "#00ffcc",
            background:    "#001100",
            surface:       "#001a00",
            dialogSurface: "#002200",
            dimSeparator:  "#003300",
        },
    },
    {
        name: "Phosphor",
        colours: {
            primary:       "#33ff99",
            planMode:      "#66ffcc",
            selection:     "#003322",
            thinking:      "#00ffaa",
            success:       "#00ff66",
            error:         "#ff3366",
            info:          "#33ccff",
            background:    "#001a10",
            surface:       "#002218",
            dialogSurface: "#002e20",
            dimSeparator:  "#003d2a",
        },
    },
    {
        name: "CRT Green",
        colours: {
            primary:       "#00ff00",
            planMode:      "#00cc44",
            selection:     "#002200",
            thinking:      "#00bb00",
            success:       "#44ff44",
            error:         "#ff4400",
            info:          "#00ffaa",
            background:    "#000800",
            surface:       "#001000",
            dialogSurface: "#001800",
            dimSeparator:  "#002800",
        },
    },
    {
        name: "CRT Amber",
        colours: {
            primary:       "#ffb300",
            planMode:      "#ff8800",
            selection:     "#2a1800",
            thinking:      "#ff9900",
            success:       "#88cc00",
            error:         "#ff3300",
            info:          "#ffdd44",
            background:    "#0f0800",
            surface:       "#160e00",
            dialogSurface: "#1e1400",
            dimSeparator:  "#2c1e00",
        },
    },
    {
        name: "Twilight",
        colours: {
            primary:       "#b4d4ee",
            planMode:      "#dcc080",
            selection:     "#2a3644",
            thinking:      "#c4a8d4",
            success:       "#90c490",
            error:         "#d48080",
            info:          "#80b0d4",
            background:    "#141c26",
            surface:       "#1a2430",
            dialogSurface: "#202c3a",
            dimSeparator:  "#2e3e50",
        },
    },
    {
        name: "Bearded Arc",
        colours: {
            primary:       "#e5cd52",
            planMode:      "#f0a060",
            selection:     "#1e2832",
            thinking:      "#b58fdd",
            success:       "#83c092",
            error:         "#e67e80",
            info:          "#7fbbb3",
            background:    "#11161c",
            surface:       "#171d24",
            dialogSurface: "#1e262e",
            dimSeparator:  "#2c3848",
        },
    },
    {
        name: "Eva Dark",
        colours: {
            primary:       "#e100ff",
            planMode:      "#00e5ff",
            selection:     "#200030",
            thinking:      "#7700ff",
            success:       "#00ff99",
            error:         "#ff0066",
            info:          "#00ccff",
            background:    "#0e0020",
            surface:       "#14002c",
            dialogSurface: "#1a0038",
            dimSeparator:  "#280050",
        },
    },
    {
        name: "Borland",
        colours: {
            primary:       "#ffff55",
            planMode:      "#55ffff",
            selection:     "#5555ff",
            thinking:      "#ff55ff",
            success:       "#55ff55",
            error:         "#ff5555",
            info:          "#55ffff",
            background:    "#0000aa",
            surface:       "#000088",
            dialogSurface: "#0000cc",
            dimSeparator:  "#1111bb",
        },
    },
    {
        name: "Kimbie Dark",
        colours: {
            primary:       "#dc9656",
            planMode:      "#f79a32",
            selection:     "#3d2b1f",
            thinking:      "#a06000",
            success:       "#889b4a",
            error:         "#d2111b",
            info:          "#7cafc2",
            background:    "#221a0f",
            surface:       "#1a1410",
            dialogSurface: "#2e2218",
            dimSeparator:  "#433420",
        },
    },
    {
        name: "Hopscotch",
        colours: {
            primary:       "#6796e6",
            planMode:      "#e9ad0c",
            selection:     "#1f2838",
            thinking:      "#cc7832",
            success:       "#76c7b7",
            error:         "#fc3737",
            info:          "#69c",
            background:    "#322931",
            surface:       "#28222a",
            dialogSurface: "#3d3240",
            dimSeparator:  "#544858",
        },
    },
    {
        name: "Flatland",
        colours: {
            primary:       "#80a0ff",
            planMode:      "#f0c060",
            selection:     "#283040",
            thinking:      "#c080ff",
            success:       "#60c080",
            error:         "#ff6080",
            info:          "#60c0e0",
            background:    "#1a2030",
            surface:       "#202838",
            dialogSurface: "#283040",
            dimSeparator:  "#38485a",
        },
    },
    {
        name: "Primer Dark",
        colours: {
            primary:       "#79c0ff",
            planMode:      "#e3b341",
            selection:     "#388bfd33",
            thinking:      "#d2a8ff",
            success:       "#56d364",
            error:         "#f85149",
            info:          "#58a6ff",
            background:    "#0d1117",
            surface:       "#161b22",
            dialogSurface: "#21262d",
            dimSeparator:  "#30363d",
        },
    },
    {
        name: "Pitch Black",
        colours: {
            primary:       "#ffffff",
            planMode:      "#dddddd",
            selection:     "#333333",
            thinking:      "#bbbbbb",
            success:       "#66ff88",
            error:         "#ff4444",
            info:          "#4488ff",
            background:    "#000000",
            surface:       "#0a0a0a",
            dialogSurface: "#141414",
            dimSeparator:  "#222222",
        },
    },
    {
        name: "Deep Purple",
        colours: {
            primary:       "#ce93d8",
            planMode:      "#ffcc02",
            selection:     "#4527a0",
            thinking:      "#e040fb",
            success:       "#00e676",
            error:         "#ff1744",
            info:          "#40c4ff",
            background:    "#120038",
            surface:       "#1a004c",
            dialogSurface: "#230060",
            dimSeparator:  "#350080",
        },
    },
    {
        name: "Brogrammer",
        colours: {
            primary:       "#e8e8d3",
            planMode:      "#ffc66d",
            selection:     "#3a3a3a",
            thinking:      "#ff98a8",
            success:       "#b4f488",
            error:         "#ff3128",
            info:          "#44b4cc",
            background:    "#131313",
            surface:       "#1c1c1c",
            dialogSurface: "#272727",
            dimSeparator:  "#3a3a3a",
        },
    },
    {
        name: "Chalk",
        colours: {
            primary:       "#b9d4f1",
            planMode:      "#ddb26f",
            selection:     "#2a3244",
            thinking:      "#c8a0e0",
            success:       "#a8d0a8",
            error:         "#d08080",
            info:          "#90b8d8",
            background:    "#151c26",
            surface:       "#1c2434",
            dialogSurface: "#222c3c",
            dimSeparator:  "#303e52",
        },
    },
    {
        name: "Monodark",
        colours: {
            primary:       "#abb2bf",
            planMode:      "#e5c07b",
            selection:     "#3e4451",
            thinking:      "#56b6c2",
            success:       "#98c379",
            error:         "#e06c75",
            info:          "#61afef",
            background:    "#282c34",
            surface:       "#21252b",
            dialogSurface: "#2c313a",
            dimSeparator:  "#4b5263",
        },
    },
    {
        name: "Xcode Dark",
        colours: {
            primary:       "#4eb0cc",
            planMode:      "#ffa14f",
            selection:     "#2f3642",
            thinking:      "#b281eb",
            success:       "#5abbad",
            error:         "#ff6961",
            info:          "#6bdfff",
            background:    "#1f2024",
            surface:       "#17181a",
            dialogSurface: "#292b30",
            dimSeparator:  "#3a3d45",
        },
    },
    {
        name: "Snazzy",
        colours: {
            primary:       "#57c7ff",
            planMode:      "#f3f99d",
            selection:     "#3a3d4d",
            thinking:      "#ff6ac1",
            success:       "#5af78e",
            error:         "#ff5c57",
            info:          "#9aedfe",
            background:    "#282a36",
            surface:       "#1e2030",
            dialogSurface: "#32344a",
            dimSeparator:  "#4e5166",
        },
    },
    {
        name: "Afterglow",
        colours: {
            primary:       "#6a9fb5",
            planMode:      "#f4bf75",
            selection:     "#4a4a5a",
            thinking:      "#aa759f",
            success:       "#90a959",
            error:         "#ac4142",
            info:          "#75b5aa",
            background:    "#2c2c2c",
            surface:       "#242424",
            dialogSurface: "#363636",
            dimSeparator:  "#4a4a4a",
        },
    },
]

// ── EXTRA BATCH ───────────────────────────────────────────────
export const EXTRA_THEMES: Theme[] = [
    {
        name: "Matte Black",
        colours: { primary:"#e0e0e0", planMode:"#c8a050", selection:"#2e2e2e", thinking:"#a0a0a0", success:"#78c878", error:"#c87878", info:"#78a8c8", background:"#111111", surface:"#1a1a1a", dialogSurface:"#222222", dimSeparator:"#333333" },
    },
    {
        name: "Espresso",
        colours: { primary:"#d4c4a8", planMode:"#c8a060", selection:"#302820", thinking:"#b0a090", success:"#88b888", error:"#c87060", info:"#80a8c8", background:"#1a1410", surface:"#221c18", dialogSurface:"#2c2420", dimSeparator:"#3c3430" },
    },
    {
        name: "Galaxy",
        colours: { primary:"#a0c8ff", planMode:"#ffc880", selection:"#202848", thinking:"#c0a0ff", success:"#80e8a0", error:"#ff8080", info:"#80d8ff", background:"#080e20", surface:"#0e1630", dialogSurface:"#141e3c", dimSeparator:"#202c50" },
    },
    {
        name: "Windsurf Dark",
        colours: { primary:"#5ac8fa", planMode:"#ffd600", selection:"#1c3a4a", thinking:"#a78bfa", success:"#4ade80", error:"#f87171", info:"#38bdf8", background:"#0c1e2a", surface:"#122636", dialogSurface:"#182e40", dimSeparator:"#224055" },
    },
    {
        name: "Coral Reef",
        colours: { primary:"#ff7c7c", planMode:"#ffb347", selection:"#2e1a18", thinking:"#ff9e9e", success:"#5cd65c", error:"#ff4545", info:"#45d4fa", background:"#180c0c", surface:"#221414", dialogSurface:"#2c1c1c", dimSeparator:"#402828" },
    },
    {
        name: "Plum",
        colours: { primary:"#b070b0", planMode:"#d4a040", selection:"#2c1830", thinking:"#d090d0", success:"#70b080", error:"#c06060", info:"#6090c0", background:"#140c18", surface:"#1c1220", dialogSurface:"#241828", dimSeparator:"#38263c" },
    },
    {
        name: "Indigo Night",
        colours: { primary:"#7986cb", planMode:"#ffb74d", selection:"#1a2060", thinking:"#9575cd", success:"#66bb6a", error:"#ef5350", info:"#42a5f5", background:"#0d1030", surface:"#121540", dialogSurface:"#181c50", dimSeparator:"#222868" },
    },
    {
        name: "Topaz",
        colours: { primary:"#57c8d3", planMode:"#ffc857", selection:"#1a3038", thinking:"#9ee8ee", success:"#70c878", error:"#d87070", info:"#57a8c8", background:"#0a1820", surface:"#102028", dialogSurface:"#162830", dimSeparator:"#223a44" },
    },
    {
        name: "Onyx",
        colours: { primary:"#c8c8e8", planMode:"#d8b870", selection:"#28284a", thinking:"#a8a8d8", success:"#78c898", error:"#d87878", info:"#78a8e8", background:"#0e0e1e", surface:"#161628", dialogSurface:"#1e1e32", dimSeparator:"#2c2c44" },
    },
    {
        name: "Aurora",
        colours: { primary:"#88d8b0", planMode:"#ffeaa7", selection:"#1a3030", thinking:"#a8c8ff", success:"#55efc4", error:"#fd79a8", info:"#74b9ff", background:"#0a1a20", surface:"#102028", dialogSurface:"#162830", dimSeparator:"#204040" },
    },
    {
        name: "Lava",
        colours: { primary:"#ff6620", planMode:"#ffaa00", selection:"#380e00", thinking:"#ff9960", success:"#60b060", error:"#ff2200", info:"#40a0d0", background:"#1a0800", surface:"#221000", dialogSurface:"#2c1400", dimSeparator:"#401c00" },
    },
    {
        name: "Dusk",
        colours: { primary:"#c8a0e8", planMode:"#e8c880", selection:"#2e2048", thinking:"#e8c0ff", success:"#80c8a0", error:"#d87898", info:"#80b0e8", background:"#181028", surface:"#1e1632", dialogSurface:"#261e3c", dimSeparator:"#382c52" },
    },
    {
        name: "Copper",
        colours: { primary:"#b87040", planMode:"#d09050", selection:"#2a1c10", thinking:"#d0a070", success:"#68a060", error:"#c05050", info:"#5880a0", background:"#140c06", surface:"#1c140e", dialogSurface:"#241c14", dimSeparator:"#362818" },
    },
    {
        name: "Mint Dark",
        colours: { primary:"#63d9a0", planMode:"#f0c060", selection:"#103028", thinking:"#a0e8c8", success:"#40d090", error:"#e06070", info:"#50b0e0", background:"#061814", surface:"#0c221c", dialogSurface:"#122c24", dimSeparator:"#1c4034" },
    },
    {
        name: "Venom",
        colours: { primary:"#80ff00", planMode:"#ccff00", selection:"#1a2e00", thinking:"#a0e840", success:"#60ff60", error:"#ff4400", info:"#00ff88", background:"#0a1400", surface:"#101c00", dialogSurface:"#162400", dimSeparator:"#223600" },
    },
    {
        name: "Stardust",
        colours: { primary:"#f0d0ff", planMode:"#ffe0a0", selection:"#302040", thinking:"#d0b0f8", success:"#a0f0c0", error:"#ff8080", info:"#80d0ff", background:"#180d28", surface:"#201438", dialogSurface:"#281c44", dimSeparator:"#3c2858" },
    },
    {
        name: "Wombat",
        colours: { primary:"#cae682", planMode:"#e5c06d", selection:"#32322c", thinking:"#d0cfc8", success:"#95e454", error:"#e5786d", info:"#8ac6f2", background:"#1c1c1c", surface:"#242424", dialogSurface:"#2e2e2e", dimSeparator:"#3e3e3e" },
    },
    {
        name: "Paraiso Dark",
        colours: { primary:"#fec418", planMode:"#e96ba8", selection:"#2f1f3e", thinking:"#bf83c1", success:"#48b685", error:"#ef6155", info:"#06b6ef", background:"#2f1f3e", surface:"#261831", dialogSurface:"#3c2851", dimSeparator:"#4e3864" },
    },
    {
        name: "Dracula Soft",
        colours: { primary:"#caa9fa", planMode:"#f1d392", selection:"#3d3f4e", thinking:"#f4a9c5", success:"#a2e3a2", error:"#f4909a", info:"#a2d8f4", background:"#252837", surface:"#1e2130", dialogSurface:"#303347", dimSeparator:"#454860" },
    },
    {
        name: "Pitch Dark Teal",
        colours: { primary:"#00b8a9", planMode:"#f8c291", selection:"#003330", thinking:"#00d4c4", success:"#00d084", error:"#e84393", info:"#0090d0", background:"#001a18", surface:"#002422", dialogSurface:"#002e2c", dimSeparator:"#004040" },
    },
    {
        name: "Moonrise",
        colours: { primary:"#d8c8b0", planMode:"#e8c068", selection:"#302820", thinking:"#c8b8d8", success:"#90c890", error:"#d88888", info:"#88b0d8", background:"#181410", surface:"#201c18", dialogSurface:"#282420", dimSeparator:"#3a3430" },
    },
    {
        name: "Pitch Dark Rose",
        colours: { primary:"#f43f5e", planMode:"#fb923c", selection:"#3f0010", thinking:"#fb7185", success:"#34d399", error:"#ff1744", info:"#38bdf8", background:"#1a0008", surface:"#240012", dialogSurface:"#2e0018", dimSeparator:"#440020" },
    },
    {
        name: "Vermillion",
        colours: { primary:"#d4503c", planMode:"#e0963c", selection:"#2e1010", thinking:"#e07060", success:"#60a860", error:"#cc2020", info:"#4878b0", background:"#160a08", surface:"#1e1010", dialogSurface:"#281616", dimSeparator:"#3a2020" },
    },
    {
        name: "Seafloor",
        colours: { primary:"#50c0b0", planMode:"#d8c050", selection:"#103030", thinking:"#80d8d0", success:"#50c870", error:"#d05060", info:"#5090d0", background:"#061818", surface:"#0c2020", dialogSurface:"#122828", dimSeparator:"#1c3c3c" },
    },
    {
        name: "Nightly",
        colours: { primary:"#9090c0", planMode:"#b8a060", selection:"#282838", thinking:"#8080b0", success:"#70a870", error:"#a86060", info:"#6088a8", background:"#141420", surface:"#1a1a28", dialogSurface:"#202030", dimSeparator:"#2e2e40" },
    },
    {
        name: "Pastel Dark",
        colours: { primary:"#a8c8f8", planMode:"#f8d8a8", selection:"#282840", thinking:"#d0a8f8", success:"#a8f8c8", error:"#f8a8a8", info:"#a8e8f8", background:"#141420", surface:"#1c1c2c", dialogSurface:"#242438", dimSeparator:"#343450" },
    },
    {
        name: "Space Cadet",
        colours: { primary:"#9eb4dd", planMode:"#e0c285", selection:"#1e2a40", thinking:"#bb99ee", success:"#88cc88", error:"#ee8888", info:"#88bbee", background:"#10161e", surface:"#161e2a", dialogSurface:"#1c2636", dimSeparator:"#2a384e" },
    },
    {
        name: "Oxide",
        colours: { primary:"#90a890", planMode:"#b8a060", selection:"#202820", thinking:"#a0b8a0", success:"#70a870", error:"#a87070", info:"#70a0b8", background:"#101810", surface:"#182018", dialogSurface:"#202820", dimSeparator:"#2e3c2e" },
    },
    {
        name: "Pitch Dark Amber",
        colours: { primary:"#ffb300", planMode:"#ff8f00", selection:"#331a00", thinking:"#ffd54f", success:"#69f0ae", error:"#ff5252", info:"#40c4ff", background:"#170d00", surface:"#201400", dialogSurface:"#291b00", dimSeparator:"#3d2800" },
    },
    {
        name: "Lazurite",
        colours: { primary:"#7da3b8", planMode:"#d4a84b", selection:"#1a2e3a", thinking:"#c09ac0", success:"#789060", error:"#c06060", info:"#5090b0", background:"#0e181e", surface:"#142028", dialogSurface:"#1a2832", dimSeparator:"#263848" },
    },
]

export const ALL_THEMES: Theme[] = [...THEMES, ...EXTRA_THEMES]

export const DEFAULT_THEME=THEMES.find((t)=>t.name==="Dracula")!